=== HacyViv29/tecweb/practicas/p16/serviciovod_ep.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
    elementFormDefault="qualified">

    <xs:complexType name="CuentaType">
        <xs:sequence>
            <xs:element name="perfiles">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="perfil" type="PerfilesType" maxOccurs="unbounded"/>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
        </xs:sequence>
        <xs:attribute name="correo" type="xs:string" use="required"/>
    </xs:complexType>

    <xs:complexType name="PerfilesType">
        <xs:attribute name="usuario" type="xs:string" use="required"/>
        <xs:attribute name="idioma" type="xs:string" use="required"/>
    </xs:complexType>

    <xs:complexType name="ContenidoType">
        <xs:sequence>
            <xs:element name="peliculas" type="PeliculasType" />
            <xs:element name="series" type="SeriesType" />
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="PeliculasType">
        <xs:sequence>
            <xs:element name="genero" type="GeneroType" maxOccurs="unbounded"/>
        </xs:sequence>
        <xs:attribute name="region" type="RegionType" use="optional" default="USA"/>
    </xs:complexType>

    <xs:complexType name="SeriesType">
        <xs:sequence>
            <xs:element name="genero" type="GeneroType" maxOccurs="unbounded"/>
        </xs:sequence>
        <xs:attribute name="region" type="RegionType" use="optional" default="USA"/>
    </xs:complexType>

    <xs:simpleType name="RegionType">
        <xs:restriction base="xs:string">
            <xs:enumeration value="MEX"/>
            <xs:enumeration value="USA"/>
            <xs:enumeration value="ESP"/>
            <xs:enumeration value="ARG"/>
            <xs:enumeration value="KOR"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:complexType name="GeneroType">
    <xs:sequence>
        <xs:element name="titulo" maxOccurs="unbounded">
            <xs:complexType>
                <xs:simpleContent>
                    <xs:extension base="xs:string">
                        <xs:attribute name="duracion" type="xs:string" use="required"/>
                    </xs:extension>
                </xs:simpleContent>
            </xs:complexType>
        </xs:element>
    </xs:sequence>
    <xs:attribute name="nombre" type="xs:string" use="required"/>
</xs:complexType>


    <xs:complexType name="CatalogoType">
        <xs:sequence>
            <xs:element name="cuenta" type="CuentaType" maxOccurs="unbounded" />
            <xs:element name="contenido" type="ContenidoType" />
        </xs:sequence>
    </xs:complexType>

    <xs:element name="CatalogoVOD" type="CatalogoType" />

</xs:schema>

=== HacyViv29/tecweb/practicas/p15/serviciovod4.xml
<?xml version="1.0" encoding="UTF-8"?>

<CatalogoVOD xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="serviciovod_ep.xsd">
    <cuenta correo="hacyviv29@gmail.com">
        <perfiles>
            <perfil usuario="Hacy" idioma="Inglés"/>
            <perfil usuario="Sher" idioma="Español"/>
        </perfiles>
    </cuenta>
    <contenido>
        <peliculas region="USA">
            <genero nombre="Ciencia Ficción">
                <titulo duracion="01:56:00">Volver al Futuro.</titulo>
                <titulo duracion="01:46:00">El proyecto Adam.</titulo>
            </genero>
            <genero nombre="Espias">
                <titulo duracion="02:09:00">Kingsman: El servicio secreto</titulo>
                <titulo duracion="02:19:00">Argylle: Agente secreto</titulo>
            </genero>
        </peliculas>
        <series region="USA">
            <genero nombre="Drama">
                <titulo duracion="00:44:00">Dr. House</titulo>
                <titulo duracion="00:48:00">Breaking Bad</titulo>
            </genero>
            <genero nombre="Super Heroes">
                <titulo duracion="0s0:50:00">Loki</titulo>
                <titulo duracion="00:22:00">Spectacular Spider-Man</titulo>
            </genero>
        </series>
    </contenido>
</CatalogoVOD>
